apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: smartcity
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: phpmyadmin
          image: phpmyadmin:latest
          ports:
            - containerPort: 80
          env:
            - name: PMA_ARBITRARY
              value: "1"
            - name: PMA_HOST
              valueFrom:
                configMapKeyRef:
                  name: smartcity-config
                  key: DB_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-service
  namespace: smartcity
spec:
  selector:
    app: phpmyadmin
  ports:
    - port: 80
      targetPort: 80