apiVersion: v1
kind: Secret
metadata:
  name: smartcity-secrets
  namespace: smartcity
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass"
  DB_PASSWORD: "rootpass"
  JWT_SECRET: "kelompok3"
  PHP_APP_KEY: "base64:zeI5WlSXFC+HAEUQeq2/G4ff0dENdkeVHQNa6eqM8s4="
  RABBITMQ_USER: "guest"
  RABBITMQ_PASSWORD: "guest"